steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/quarentime-registry/${_IMAGE_NAME}', '-f', '${_PROJECT}.Dockerfile', '.']
images:
- "gcr.io/quarentime-registry/${_IMAGE_NAME}"